### ISSUE TITLE
Completely disable eventbrite if not used

### ISSUE THREAD

**Issue by yarikoptic** [sparkletown/sparkle#1390]
Somewhat of a complement in motivation to #1388 (stripe):  while loading a page noted browser saying waiting on eventbrite.
```shell
$> git grep eventbr
package-lock.json:    "react-eventbrite-popup-checkout": {
package-lock.json:      "resolved": "https://registry.npmjs.org/react-eventbrite-popup-checkout/-/react-eventbrite-popup-checkout-1.0.5.tgz",
package.json:    "react-eventbrite-popup-checkout": "^1.0.5",
public/index.html:    <script src="https://www.eventbrite.co.uk/static/widgets/eb_widgets.js"></script>
src/components/organisms/GiftTicketModal/GiftTicketModal.tsx:          "https://www.eventbrite.com/e/sparkleverse-2020-online-burn-tickets-117154948605"
src/react-app-env.d.ts:declare module "react-eventbrite-popup-checkout" {
```
Would be nice to disable that for `env/ohbm` since afaik also not used ("burn-tickets" in above suggest burning man specific venue setup)

**Comment by 0xdevalias** [comment]
I'm not deeply familiar with how the eventbrite code works within the app currently.

The dependency from `package.json` appears to be:

- https://github.com/wizardrylabs/react-eventbrite-popup-checkout

That shouldn't have any real impact on things if it's not being used, so should be fine to leave.

Similarly the string in the `GiftTicketModal` component shouldn't matter.

The script in `public.index.html` (`https://www.eventbrite.co.uk/static/widgets/eb_widgets.js`) is likely what you're seeing the 'waiting to load' for. I'm not immediately aware of what (if anything) that is needed/used for within the app.

Googling for the string lead me to this page:

- https://www.eventbrite.com/platform/docs/embedded-checkout
  - > Using the Eventbrite API, you can embed a ticket checkout widget in your app or website. This is done by including HTML code with a Javascript call and the appropriate attributes. The Javascript call is `https://www.eventbrite.com/static/widgets/eb_widgets.js`

Loading this in the `.html` file as is currently done isn't a very 'Reacty' way to do things, and makes it harder to selectively choose to load/not load.

I would expect that `react-eventbrite-popup-checkout` is likely the 'solution' to this, and since it doesn't mention needing to manually include the `eb_widgets.js` in it's setup instructions, it wouldn't surprise me if it already handles that within its own code.

Looking at the code, that seems to be exactly what it does:

- https://github.com/wizardrylabs/react-eventbrite-popup-checkout/blob/master/src/index.jsx#L22-L44

As well as defaulting to opening the eventbrite page manually if the `eb_widgets.js` tools aren't loaded:

- https://github.com/wizardrylabs/react-eventbrite-popup-checkout/blob/master/src/index.jsx#L46-L54

Since this code is using React's `componentWillMount`/`componentWillUnmount`/etc handlers (see https://github.com/wizardrylabs/react-eventbrite-popup-checkout/issues/4), it's pretty dated, and seems it's not really actively maintained. The library doesn't seem to actually do a whole lot though, so it would be fairly easy to re-implement the logic we need from it.

It seems it's contributing a good `5.3kB ` (minified+gzipped) to our bundle size, which we could probably get rid of by re-implementing it ourselves):

- https://bundlephobia.com/result?p=react-eventbrite-popup-checkout@1.0.5

There doesn't seem to be any code that uses `EBWidgets` directly when searching the codebase, so that makes me even more confident that the `<script>` in `public/index.html` isn't used right now:

- https://github.com/sparkletown/sparkle/search?q=EBWidgets

Searching the codebase for `eventbrite` (as you did with your grep):

- https://github.com/sparkletown/sparkle/search?q=eventbrite

It doesn't even look like we're using `react-eventbrite-popup-checkout` at the moment at all:

- https://github.com/sparkletown/sparkle/blob/staging/src/components/organisms/GiftTicketModal/GiftTicketModal.tsx#L13-L22

**Comment by 0xdevalias** [comment]
@yarikoptic FYI: I've just created https://github.com/sparkletown/sparkle/pull/1400 to cleanup the legacy/unused eventbrite code. It'll likely get reviewed and merged sometime early next week, then deployed into `env/ohbm` when we next deploy code there.
