### ISSUE TITLE
Search results in poster hall are not based on actual data

### ISSUE THREAD

**Issue by yarikoptic** [sparkletown/sparkle#1391]
Searching for "ayzasdasdaaaaaa" gave me 3 posters.  May be expected ATM (i.e. search is not really there)

**Comment by 0xdevalias** [comment]
Relevant files:

- https://github.com/sparkletown/sparkle/blob/staging/src/components/templates/PosterHall/PosterHall.tsx
- https://github.com/sparkletown/sparkle/blob/staging/src/components/templates/PosterHall/components/PosterHallSearch/PosterHallSearch.tsx
- https://github.com/sparkletown/sparkle/blob/staging/src/hooks/posters.ts

---

@yarikoptic If you look at the code in `useConnectPosterVenues`, you can see where we connect to the firestore database:

- https://github.com/sparkletown/sparkle/blob/staging/src/hooks/posters.ts#L13-L26

If you look at the code in `usePosters`, you can see where the code for the search is performed:

- https://github.com/sparkletown/sparkle/blob/staging/src/hooks/posters.ts#L71-L87

This uses `Fuse.js`, which is a fuzzy-search library:

- https://fusejs.io/
  - > Fuse.js is a powerful, lightweight fuzzy-search library, with zero dependencies.
  - > Generally speaking, fuzzy searching (more formally known as approximate string matching) is the technique of finding strings that are approximately equal to a given pattern (rather than exactly).
  - https://github.com/krisk/fuse

---

@yarikoptic My initial guess would be that the `ayzasdasdaaaaaa` string that you're seeing return posters is based on the fuzzy-search, and that it is just determined to be approximately equal. Would that seem like it could apply here?

**Comment by 0xdevalias** [comment]
@yarikoptic Based on what I shared in https://github.com/sparkletown/sparkle/issues/1391#issuecomment-841601363 do you still consider this to be an 'issue', or can I close this?

**Comment by yarikoptic** [comment]
I will look in detail tomorrow, but I am afraid that fuzzy search might hurt more than help: people will be looking for exact names and terms. Getting hits which have no relationship to the query of interest unlikely would be taken as a feature to admire: eg I tried to search for my last name and there were lots of hits, not related.

**Comment by 0xdevalias** [comment]
> I am afraid that fuzzy search might hurt more than help: people will be looking for exact names and terms. 

@yarikoptic Fuzzy search is the implementation we have currently, and is generally what most search features use. The results should be ranked by their 'closeness' to the match (and if they aren't that would be a bug), so in the case of there being an 'exact match', that should be ranked higher in the search results.

**Comment by yarikoptic** [comment]
Can you tell why  ayzasdasdaaaaaa is anyhow valuably close to any of those 3 posters? May the fuzzy distance limit could be adjusted so only smaller fuzz is allowed? 
Also "no exact hits" is information some might need -  may be it is easy to either group exact vs fuzzy hits or annotate somehow each hit on either of it is exact or how fuzzy?

**Comment by yarikoptic** [comment]
An analogy - if you get to a doctor, do you want a doctor give you exact singular prescription, 
may be with recommendations on some optional supplements and no prescription if he had no clue, or a list of prescriptions ordered in order of closeness (even when the doc apparently had no clue about 90% of your symptoms) so you could try and drill down on your own if anything would work? My point is that fuzzy hit is good when you know what is fuzzy.

**Comment by 0xdevalias** [comment]
> This uses `Fuse.js`, which is a fuzzy-search library:
> 
> * https://fusejs.io/
>   
>   * > Fuse.js is a powerful, lightweight fuzzy-search library, with zero dependencies.
>   * > Generally speaking, fuzzy searching (more formally known as approximate string matching) is the technique of finding strings that are approximately equal to a given pattern (rather than exactly).
>   * https://github.com/krisk/fuse

@yarikoptic You’re welcome to explore the library and feature and see if you can answer some of your questions/concerns for yourself.

From my perspective, this is how the feature is implemented/works, and I don’t know that I have the bandwidth to explore deeper than that otherwise.

If you find a solution/potential solution then by all means raise it here and I’ll check it out and see if it makes sense/would work for the system.

**Comment by yarikoptic** [comment]
FWIW, with 
```diff
diff --git a/src/hooks/posters.ts b/src/hooks/posters.ts
index a4edb158..f4e4fb54 100644
--- a/src/hooks/posters.ts
+++ b/src/hooks/posters.ts
@@ -72,6 +72,12 @@ export const usePosters = (posterHallId: string) => {
     () =>
       new Fuse(filteredPosterVenues, {
         keys: ["poster.title", "poster.authorName", "poster.categories"],
+        threshold: 0.4,       // default 0.6: brings too distant if anyhow related hits
+        ignoreLocation: true,  // default False: True - to search ignoring location of the words.
+                               // Otherwise can't find a word in a sentence
+        // includeScore: true   // so it could be displayed!?
+        // distance: 40        //  default 100 - ignored if ignoreLocation: true
+        // useExtendedSearch: true // might be neat!
       }),
     [filteredPosterVenues]
   );
```
getting some sense of the results.  Enabling ExtendedSearch also allows for some workarounding.
But overall - still not satisfied since feels like a gamble. E.g. 
- searching for `Last First` instead of `First Last` author would either result in no hits whatsoever or unrelated ones. I guess the fuse considers it as a phrase.
- adding a space at the end of the query immediately changes the results, some times making them disappear or grow (may be could be mitigated ad-hoc by trim'ing the search query)
- if enabling extended search, prior query `word_from_title word_from_name` no longer hits anything
- it seems that the same query might be returning different results... (not yet 100% sure - may be was some "need reload" fluke)
- it seems to be possible to specify the key to match in... searching for `authorName:Tsai` hits a single poster, but if I add  `title:connectivity` since poster title has that word - it just finds some other poster from a different author...

So overall it remains a **very odd** experience from this search and I still feel that even a simple search by a bag of words would have been more intuitive IMHO.
