### ISSUE TITLE
[env/ohbm] BUG: User icons misrepresenting presence

### ISSUE THREAD

**Issue by effigies** [sparkletown/sparkle#1644]
I have had / heard these experiences today:

1) Enter a social room, and see nobody at a table. Leave.
1) Enter a social room, and see nobody / few people at a table. Join to find a very full table.
1) Attempt to join a table with people in it. Nobody at table.

I suspect this is fallout of #1630, and the performance improvements undoubtedly make up for the confusion.

That said, the social aspect is pretty critical to engagement, and I'm worried that people are trying to engage and are misperceiving spaces as empty, leaving, and ensuring the spaces are emptier than they would otherwise be.

**Comment by yarikoptic** [comment]
I am 99% certain it is a side effect of #1630 and thus relevant only to OHBM2021 (env/ohbm branch) event.  "No free lunch" effect -- sacrifices had to be made, not sure if it would be mitigated before the completion of the event. Might be worth minting/using a label `ohbm` for such issues to simplify their triage in the future whenever a stop-gap measure is removed and a proper "fix" to scale up to the unique demand of the OHBM is implemented.

**Comment by soichih** [comment]
I agree that this is a rather critical side effect of #1630 .. I could try to come up a simple way to mitigate it (or ideally someone from spakle implement the fix), but given sparkle had to go out of their way to get our *custom* branch released, I am not sure if they are willing to do anything for OHBM at this point (I doubt it?)

**Comment by 0xdevalias** [comment]
Given how close to the end of the conference it’s unlikely to be able to land in time. We’re super swamped with work from a bunch of different directions at the moment, and given this ‘fallout’ only applies to the hack fix on env/ohbm, and we plan on fixing things properly in the main code branch to avoid side effects/fallout/etc, it shouldn’t be an issue on the wider platform ongoing.

Still worth leaving this issue open for now for visibility though. I’ll handle triage/context/cleanup on things when the chaos dies down a bit.

If you did want to ‘label’ these OHBM specific things, I tend to prefix the issue title with [env/ohbm]; so that would be a good pattern to follow.

**Comment by colinhowe** [comment]
We've done substantial redesign of the platform since this issue was opened. I'm going to close this as stale.
